### PR TITLE
Version 3 Rewrite

### PR DESCRIPTION
**Pull request by JonathanTreffler**
implements #21 

## Todo

- [x] Implement boilerplate code for sidebar

- [x] implement sidebar loader

- [x] call Sidebar loader

- [x] install necessary dependencies (vuejs, webpack)

- [x] add webpack configuration

- [x] add build scripts

- [x] Add functionality to sidebar

- [x] Styling

- [x] Final Testing

<a href="https://gitpod.io/#https://github.com/JonathanTreffler/sharerenamer/pull/31"></a>

### CODE REVIEW

**Comment by DecaTec** [comment]
Can we merge this or should we wait until all the todos are done?

**Comment by JonathanTreffler** [comment]
Since it is not ready to be published to the app store, i think we should keep it in this branch and keep master stable.

**Comment by DecaTec** [comment]
OK, then we don't merge (yet).

Have you received my mail? ;-)

**Comment by JonathanTreffler** [comment]
Development is going well. The build setup and loading of the sidebar Tab is done. The only thing left is the UI.

**Comment by ei8fdb** [comment]
> Development is going well. The build setup and loading of the sidebar Tab is done. The only thing left is the UI.

If you need help testing, post here and I'll be happy to test.

**Comment by JonathanTreffler** [comment]
image

Everything works now and the UI is implemented.

**Comment by JonathanTreffler** [comment]
I am just a bit worried about the security of the backend.

@DecaTec How confident are you the backend can't be used to rename tokens you are not supposed to be able to edit.

**Comment by JonathanTreffler** [comment]
Also, I will need to create an icon for the Tab.
I have tried combining the share icon with the edit icon, but I have not found a nice looking way so far.

**Comment by JonathanTreffler** [comment]
If anyone wants to test it, here is an alpha version:

[sharerenamer.zip](https://github.com/JonathanTreffler/sharerenamer/files/6797153/sharerenamer.zip)

hope it works xD

**Comment by AntoineD-dot-fr** [comment]
Some ideas of icons that could do the trick (from Font-Awesome) : 
https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/hand-sparkles.svg
https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/link.svg
https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/edit.svg
https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/pen-nib.svg

**Comment by RiCkYB-667** [comment]
> If anyone wants to test it, here is an alpha version:
> 
> [sharerenamer.zip](https://github.com/JonathanTreffler/sharerenamer/files/6797153/sharerenamer.zip)
> 
> hope it works xD

Doesn't seem to be able to detect shares for me. No rename function appears regardless of anything. It keeps saying No shares to rename. I tried with brand new upload and sharelinks.
Any way i can help debugging this?
NC version 21.0.1

**Comment by JonathanTreffler** [comment]
> > If anyone wants to test it, here is an alpha version:
> > [sharerenamer.zip](https://github.com/JonathanTreffler/sharerenamer/files/6797153/sharerenamer.zip)
> > hope it works xD
> 
> Doesn't seem to be able to detect shares for me. No rename function appears regardless of anything. It keeps saying No shares to rename. I tried with brand new upload and sharelinks.
> Any way i can help debugging this?
> NC version 21.0.1

I have not tested it on Version 21. I will test it now. Thanks for reporting this.

**Comment by JonathanTreffler** [comment]
I just tested it on Nextcloud 21.0.3 and it works fine for me.
The reason it might not have worked for you is, that currently you have to close and open the sidebar so the shares refresh.

**Comment by ei8fdb** [comment]
> Also, I will need to create an icon for the tab.

Can you give some detail of which tab you mean? You mean the "share tab" is [the screenshot above](https://github.com/JonathanTreffler/sharerenamer/pull/31#issuecomment-877818166)?

**Comment by JonathanTreffler** [comment]
> One tangential question: would it be possible to display the share rename _in_ the share tab?

Nothing is impossible and I do plan to see if I can implement it in the future, but it would be a ton of work and bring the old problem back, that pretty much every major Nextcloud update will break the app.

**Comment by JonathanTreffler** [comment]
> Can you give some detail of which tab you mean? You mean the "share tab" is [the screenshot above](https://github.com/JonathanTreffler/sharerenamer/pull/31#issuecomment-877818166)?

The tab in the screenshot above

**Comment by ei8fdb** [comment]
> > One tangential question: would it be possible to display the share rename _in_ the share tab?
> 
> Nothing is impossible and I do plan to see if I can implement it in the future, but it would be a ton of work and bring the old problem back, that pretty much every major Nextcloud update will break the app.

Yep, I kinda figured that was the reason for implementing it in a separate tab. No problem, just curious.

**Comment by ei8fdb** [comment]
> > Can you give some detail of which tab you mean? You mean the "share tab" is [the screenshot above](https://github.com/JonathanTreffler/sharerenamer/pull/31#issuecomment-877818166)?
> 
> The tab in the screenshot above

I think any of these as suggested by @AntoineD-dot-fr above would be fine:

https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/edit.svg
https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/hand-sparkles.svg

For the future (as a suggestion) - you could create a design job requesting a visual designer to design a logo for Share Renamer. 

I'm a member of opensourcedesign.net, a community of UX designers, visual and graphic designers, and we run a jobs board (for free), at www.opensourcedesign.net/jobs

**Comment by RiCkYB-667** [comment]
> I just tested it on Nextcloud 21.0.3 and it works fine for me.
> The reason it might not have worked for you is, that currently you have to close and open the sidebar so the shares refresh.

I have update everything to the latest (NC to 21.0.3 and all apps), redownloaded your zip, made sure all linux permissions are fine, still i'm out of luck.
Any tips on where to search for clues?
Thank you so much!

image

**Comment by JonathanTreffler** [comment]
can you attach a screenshot of the sharing tab ?

> > I just tested it on Nextcloud 21.0.3 and it works fine for me.
> > The reason it might not have worked for you is, that currently you have to close and open the sidebar so the shares refresh.
> 
> I have update everything to the latest (NC to 21.0.3 and all apps), redownloaded your zip, made sure all linux permissions and ownerships are fine, still i'm out of luck.
> Any tips on where to search for clues?
> Thank you so much!
> 
> image

**Comment by DecaTec** [comment]
> I am just a bit worried about the security of the backend.
> 
> @DecaTec How confident are you the backend can't be used to rename tokens you are not supposed to be able to edit.

In earlier verions, the link itself was provided by the "share UI". That was the reason why you always got the right link.
Now, the UI for ShareRenamer is located in a separate tab. In this case, you have to make sure, that you only show the shared links of the user.
I don't know if there is any user relation in the database table.

**Comment by RiCkYB-667** [comment]
> can you attach a screenshot of the sharing tab ?
> 
> > > I just tested it on Nextcloud 21.0.3 and it works fine for me.
> > > The reason it might not have worked for you is, that currently you have to close and open the sidebar so the shares refresh.
> > 
> > 
> > I have update everything to the latest (NC to 21.0.3 and all apps), redownloaded your zip, made sure all linux permissions and ownerships are fine, still i'm out of luck.
> > Any tips on where to search for clues?
> > Thank you so much!

Sure:
image

**Comment by JonathanTreffler** [comment]
> > I am just a bit worried about the security of the backend.
> > @DecaTec How confident are you the backend can't be used to rename tokens you are not supposed to be able to edit.
> 
> In earlier verions, the link itself was provided by the "share UI". That was the reason why you always got the right link.
> Now, the UI for ShareRenamer is located in a separate tab. In this case, you have to make sure, that you only show the shared links of the user.
> I don't know if there is any user relation in the database table.

The new version doesn't read in the shares database. It uses the same API as the Sharing Tab.

**Comment by DecaTec** [comment]
> > > I am just a bit worried about the security of the backend.
> > > @DecaTec How confident are you the backend can't be used to rename tokens you are not supposed to be able to edit.
> > 
> > 
> > In earlier verions, the link itself was provided by the "share UI". That was the reason why you always got the right link.
> > Now, the UI for ShareRenamer is located in a separate tab. In this case, you have to make sure, that you only show the shared links of the user.
> > I don't know if there is any user relation in the database table.
> 
> The new version doesn't read in the shares database. It uses the same API as the Sharing Tab.

OK, then this should be save, assuming that the API only povides share links the user is supposed to change.

**Comment by gaellafond** [comment]
Thank you very much @JonathanTreffler  and @DecaTec . I can see you did a lot of work on it recently. Unfortunately, I can't compile it. When I do a "make all", it gives me a lot of errors:
`
✖ 97 problems (89 errors, 8 warnings)
  75 errors and 6 warnings potentially fixable with the `--fix` option.
`

Would it be possible to share the latest compiled version?

**Comment by gaellafond** [comment]
Here is a complete list of warnings and errors I get at compile time:
```
WARNING in *REDACTED*/sharerenamer/src/SharerenamerTab.vue
   5:20   warning  Expected 1 line break after opening tag (`<template>`), but no line breaks found    vue/singleline-html-element-content-newline
   5:59   warning  Expected 1 line break before closing tag (`</template>`), but no line breaks found  vue/singleline-html-element-content-newline
   7:103  warning  Attribute 'editPlaceholder' must be hyphenated                                      vue/attribute-hyphenation
  25:13   warning  The property or function OC.generateUrl was deprecated in Nextcloud 19.0.0          @nextcloud/no-deprecations
  28:2    warning  The "components" property should be above the "data" property on line 19            vue/order-in-components
  58:27   warning  The global property or function $ was deprecated in Nextcloud 19.0.0                @nextcloud/no-deprecations
  62:29   warning  Missing trailing comma                                                              comma-dangle
  94:6    warning  Missing trailing comma                                                              comma-dangle

✖ 92 problems (84 errors, 8 warnings)
  71 errors and 6 warnings potentially fixable with the `--fix` option.

ERROR in *REDACTED*/sharerenamer/src/SharerenamerTab.vue
    7:86   error  ':editable' should be on a new line                 vue/max-attributes-per-line
    7:103  error  'editPlaceholder' should be on a new line           vue/max-attributes-per-line
    7:127  error  'icon' should be on a new line                      vue/max-attributes-per-line
    7:145  error  '@update:title' should be on a new line             vue/max-attributes-per-line
   12:37   error  Extra semicolon                                     semi
   14:81   error  Extra semicolon                                     semi
   25:28   error  Strings must use singlequote                        quotes
   50:1    error  Expected indentation of 1 tab but found 4 spaces    indent
   51:1    error  Expected indentation of 2 tabs but found 8 spaces   indent
   51:9    error  Expected method shorthand                           object-shorthand
   51:26   error  Identifier 'old_token' is not in camel case         camelcase
   51:37   error  Identifier 'new_token' is not in camel case         camelcase
   52:8    error  'self' is never reassigned. Use 'const' instead     prefer-const
   52:19   error  Extra semicolon                                     semi
   54:4    error  Unexpected console statement                        no-console
   54:37   error  Extra semicolon                                     semi
   56:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   57:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   57:13   error  Unexpected var, use let or const instead            no-var
   57:33   error  Extra semicolon                                     semi
   58:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   58:13   error  Unexpected var, use let or const instead            no-var
   58:27   error  '$' is not defined                                  no-undef
   59:1    error  Expected indentation of 4 tabs but found 16 spaces  indent
   59:37   error  Strings must use singlequote                        quotes
   60:1    error  Expected indentation of 4 tabs but found 16 spaces  indent
   60:23   error  A space is required after '{'                       object-curly-spacing
   60:24   error  Unnecessarily quoted property 'old_token' found     quote-props
   60:24   error  Expected property shorthand                         object-shorthand
   60:35   error  Extra space after key 'old_token'                   key-spacing
   60:49   error  Unnecessarily quoted property 'new_token' found     quote-props
   60:49   error  Expected property shorthand                         object-shorthand
   60:60   error  Extra space after key 'new_token'                   key-spacing
   60:72   error  A space is required before '}'                      object-curly-spacing
   61:1    error  Expected indentation of 4 tabs but found 16 spaces  indent
   62:1    error  Expected indentation of 4 tabs but found 16 spaces  indent
   63:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   63:15   error  Extra semicolon                                     semi
   64:1    error  Trailing spaces not allowed                         no-trailing-spaces
   65:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   66:1    error  Expected indentation of 4 tabs but found 16 spaces  indent
   67:1    error  Expected indentation of 4 tabs but found 16 spaces  indent
   67:29   error  Extra semicolon                                     semi
   69:5    error  Expected space(s) after "if"                        keyword-spacing
   69:15   error  Expected '===' and instead saw '=='                 eqeqeq
   69:18   error  Strings must use singlequote                        quotes
   70:6    error  Unexpected console statement                        no-console
   70:50   error  Extra semicolon                                     semi
   71:46   error  Identifier 'new_token' is not in camel case         camelcase
   71:55   error  Extra semicolon                                     semi
   73:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   73:15   error  Extra semicolon                                     semi
   75:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   75:35   error  There should be no space after this paren           space-in-parens
   75:53   error  There should be no space before this paren          space-in-parens
   76:1    error  Expected indentation of 4 tabs but found 16 spaces  indent
   76:104  error  Extra semicolon                                     semi
   77:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   77:15   error  Extra semicolon                                     semi
   78:1    error  Trailing spaces not allowed                         no-trailing-spaces
   79:1    error  Expected indentation of 3 tabs but found 12 spaces  indent
   79:26   error  Extra semicolon                                     semi
   80:1    error  Expected indentation of 2 tabs but found 8 spaces   indent
   82:8    error  'self' is never reassigned. Use 'const' instead     prefer-const
   82:19   error  Extra semicolon                                     semi
   84:4    error  Unexpected console statement                        no-console
   84:25   error  Extra semicolon                                     semi
   85:28   error  Extra semicolon                                     semi
   87:14   error  Strings must use singlequote                        quotes
   89:14   error  Strings must use singlequote                        quotes
   96:5    error  Unexpected console statement                        no-console
   96:26   error  Extra semicolon                                     semi
   97:1    error  Trailing spaces not allowed                         no-trailing-spaces
   98:21   error  Extra semicolon                                     semi
  100:5    error  Expected space(s) after "for"                       keyword-spacing
  100:13   error  'share' is never reassigned. Use 'const' instead    prefer-const
  101:6    error  Unexpected console statement                        no-console
  101:24   error  Extra semicolon                                     semi
  103:6    error  Expected space(s) after "if"                        keyword-spacing
  107:9    error  Extra semicolon                                     semi
  114:33   error  Extra semicolon                                     semi
  115:6    error  Extra semicolon                                     semi
  117:1    error  Expected indentation of 1 tab but found 4 spaces    indent
  126:9    error  Newline required at end of file but not found       eol-last

*REDACTED*/sharerenamer/src/main.js
   2:32  error  "@nextcloud/l10n" is extraneous                             node/no-extraneous-import
  10:7   error  'sharerenamerTab' is never reassigned. Use 'const' instead  prefer-const
  35:5   error  Expected space or tab after '//' in comment                 spaced-comment
  36:16  error  Extra semicolon                                             semi
  41:3   error  Newline required at end of file but not found               eol-last

✖ 97 problems (89 errors, 8 warnings)
  75 errors and 6 warnings potentially fixable with the `--fix` option.

webpack 5.43.0 compiled with 1 error and 1 warning in 6217 ms
make: *** [*REDACTED*/sharerenamer/Makefile:64: build-js-production] Error 1
```

**Comment by gaellafond** [comment]
I fixed all the errors and most warnings. I didn't want to re-write the JQuery ajax line using "axios" so I simply add the following comment above:
```
// eslint-disable-next-line
const request = $.ajax({
    ...
```

I can now compile it and test it.

**Comment by gaellafond** [comment]
I found an issue, which I believe is related to NC 21:
```
			axios.get('/ocs/v2.php/apps/files_sharing/api/v1/shares', {
				params: {
					format: 'json',
					path: this.fileInfo.path + this.fileInfo.name,
					shared_with_me: false,
					subfiles: false,
					reshares: true,
				},
			}).then(function(response) {
```
That returns a 404, probably because NC 21 do not manage slashes "/" the same way.

According to what I found in NC source, we need to explicitly add the slash, and remove double if any for backward compatibility. It should be like this:
```
			axios.get(generateOcsUrl('apps/files_sharing/api/v1', 2) + '/shares', {
				params: {
					format: 'json',
					path: (this.fileInfo.path + '/' + this.fileInfo.name).replace('//', '/'),
					shared_with_me: false,
					subfiles: false,
					reshares: true,
				},
			}).then(function(response) {
```

NOTE: I don't think the `generateOcsUrl` is necessary, but that's probably more robust than guessing the URL. The `generateOcsUrl` needs to be added with an import:
```
import { generateOcsUrl } from '@nextcloud/router'
```

**Comment by gaellafond** [comment]
In "SharerenamerTab.vue"
```
	beforeDestroy() {
		try {
			this.tab.$destroy()
		} catch (error) {
			console.error('Unable to unmount Sharerenamer tab', error)
		}
	},
```

`this.tab` doesn't exist.

**Comment by JonathanTreffler** [comment]
Very nice work. A lot of these thing you fixed were not strictly necessary. They were just eslint and stylelint errors. They exist to keep a uniform Codinh style across all nextcloud apps, wich use the nextcloud Organisation presets. They don't actually block the build process, but they were things i wanted to fix before releasing the app. So great job :)

**Comment by JonathanTreffler** [comment]
How do you plan to add your changes to this PR ? Do you want to fork this repository, push your changes and create a PR to the v3 branch ? Alternatively you could send the folder to me as a zip and i take care of it. (I don't know how experienced you are with git)

**Comment by gaellafond** [comment]
Thanks @JonathanTreffler . I'm off for today. I will look into it tomorrow. I would prefer sending you a ZIP since I only made changes to the 2 files in "/src". That would be easier.

I'm new with NPM, eslint, Vue.js, NextCloud. When I saw the compilation errors, I assume it was not compiling. I should have double check lol. The learning curve is steep.

**Comment by gaellafond** [comment]
The modified source files.
There is still work to do. I didn't try to fix the JQuery request or the "this.tab" property which doesn't exist. But at least it works with the following modifications.
[sharerenamer-src.zip](https://github.com/JonathanTreffler/sharerenamer/files/6819504/sharerenamer-src.zip)

**Comment by gaellafond** [comment]
@JonathanTreffler To make the app callable through API calls, we need to add the @NoCSRFRequired annotation to the rename method in _lib/Controller/RenameController.php_
```
    /**
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @param string $title
     * @param string $content
     */
    public function rename() {
        return $this->service->rename($_POST['old_token'], $_POST['new_token']);
    }
```

**Comment by JonathanTreffler** [comment]
> @JonathanTreffler To make the app callable through API calls, we need to add the @NoCSRFRequired annotation to the rename method in _lib/Controller/RenameController.php_
> 
> ```
>     /**
>      * @NoAdminRequired
>      * @NoCSRFRequired
>      *
>      * @param string $title
>      * @param string $content
>      */
>     public function rename() {
>         return $this->service->rename($_POST['old_token'], $_POST['new_token']);
>     }
> ```

Are you sure ?

The documentation states:

> Using CSRF one can trick a user into executing a request that they did not want to make. Thus every POST and GET request needs to be protected against it. The only places where no CSRF checks are needed are in the main template, which is rendering the application, or in externally callable interfaces.

So as far as i understand the CSRF check should stay !?

**Comment by JonathanTreffler** [comment]
> There is still work to do. I didn't try to fix the JQuery request or the "this.tab" property which doesn't exist. But at least it works with the following modifications.

I pushed it to this PR in 576808f

**Comment by gaellafond** [comment]
When you try to call the "rename" function from an external point, from a curl function in a script for example, NextCloud returns the error: "CSRF check failed". Adding that simple line allowed it to work.

Example:
```
curl -s -u USER:PASSWORD -X POST -d "old_token=jsdfhshfsjkl&new_token=MyLink" "http://localhost/apps/sharerenamer/rename"
```

If you can call the "rename" function from an external script, without that annotation, I would like to know how you are doing it.

**Comment by JonathanTreffler** [comment]
Yes, but that is by Design.
Other apps implement seperate APIs for external endpoints.
I will look into it and find a solution.

**Comment by gaellafond** [comment]
Thanks @JonathanTreffler 
What could be the issue of opening the "rename" function? Is there any security concerns?
In our case, we only need an API to be able do perform our migration, so we can modify the source or the App for the migration then go back to the legitimate plugin. But I think there is cases where a rename API would be useful. There is an API to create share, but there is no way to decide what the token of the share will be. Opening that rename API (or other end-point offering the same functionality) would fix that issue.

**Comment by JonathanTreffler** [comment]
> Is there any security concerns?

That is the part I am currently not sure about. I will need to think about it.

**Comment by RiCkYB-667** [comment]
Should this be working on NC 21.0.3 with gellafond's modified src files? I am trying, but no luck yet :)

**Comment by gaellafond** [comment]
I can confirm what RiCkYB-667 said: the latest v3 commit is not working for me either. My old modified version is still working, so I can use it to compare with the v3 branch to see what is different. I will spend some time on it tomorrow and hopefully find out what need to be done to make it work with NC 21.

**Comment by RiCkYB-667** [comment]
> I can confirm what RiCkYB-667 said: the latest v3 commit is not working for me either. My old modified version is still working, so I can use it to compare with the v3 branch to see what is different. I will spend some time on it tomorrow and hopefully find out what need to be done to make it work with NC 21.

Hey there @gaellafond !
Did you by any chance manage to find the errors?
It would be nice to know what's up! ;)
Would really love to be able to rename those pesky links...

Thank you!

**Comment by gaellafond** [comment]
@RiCkYB-667 Sorry for late reply. I'm currently spending some time looking at it. I'm comparing my working version with the latest commit from this branch, but I don't quite understand what prevent this one from working. The structure is very different, but the code looks the same. I believe there it needs to be compiled in a very specific way and I don't know the process.

The sharerenamer app have another big issue for us. The shares are limited to 32 characters due to DB field limitation. We could increase the field size, but changing the DB schema is risky. Future NextCloud updates could revert the schema, which would cause shared links to fail.

We are planning to implement our own app. The idea, at this point, is to create some sort of "Proxy". Instead of changing the share in the DB, we will add a public API which redirect the named link to the shared hash URL.

**Comment by JonathanTreffler** [comment]
> @RiCkYB-667 Sorry for late reply. I'm currently spending some time looking at it. I'm comparing my working version with the latest commit from this branch, but I don't quite understand what prevent this one from working. The structure is very different, but the code looks the same. I believe the code needs to be compiled in a very specific way and I don't know the process.

The compilation process Is quite simple. Just run:
`npm ci`
and then
`npm run build`

Here's a compiled version of the latest commit of this PR ready to go: [sharerenamer.zip](https://github.com/JonathanTreffler/sharerenamer/files/7216628/sharerenamer.zip)

That is probably the reason why the testing on NC21 didn't work for anyone but me. The last zip i provided you all for testing was compiled, but after @gaellafond 's testing i didn't create another compiled release.

**Comment by gaellafond** [comment]
Thank you very much @JonathanTreffler . I must be doing something wrong. I pull the latest version of the project and re-compiled it / redeployed it again this morning, but still no success. I tried your pre-compiled version and it's working. I compared the version I compiled (found in sharerenamer/build/artifacts/sign/sharerenamer) with the version you provided and they are completely different. Pretty much none of the files in your build are in my build.

I assumed the compiler was not actually doing anything so I manually deleted the build folder and recompiled it. It didn't trigger any compile error but the build folder was not recreated.

So, I still don't understand the build process. What is the "npm run build" supposed to do? Where should the compiled version be after compilation? Where is the "build" folder coming from? (It's not on Git, so I assume it was created from one of my numerous attempts at building the project...)

I assume most of those questions are standard knowledge for NextCloud, or even npm. I have very little experience with those at the moment. I need deeper explanations.

**Comment by gaellafond** [comment]
I tried to run "make all" but it ended with an error:
```make: *** No rule to make target 'test', needed by 'all'.  Stop.```

I edited the Makefile. There is indeed no "test" defined in the file, so I assume the "all" goal is not part of the build process otherwise you would have fix it. None the less, I removed the "test" at the end of the "all" goal and re-run the "make all" command. It completed without errors, but the build folder is still not re-created.

**Comment by gaellafond** [comment]
I managed to get it to work. Here is what I did:
```
$ git clone https://github.com/JonathanTreffler/sharerenamer.git
$ cd sharerenamer/
$ git checkout v3
$ npm ci
$ npm run build
$ rm -R node_modules
```

Then I deploy the whole project folder to NextCloud `apps` folder.

Usually, when you compile an app, it generate a deployable artifact. I was not expecting to have to deploy the whole project. I deleted the `node_modules` folder because it was not in the build you provided, and because it was very big (~150MB).

My artifact do not have the "vendor" folder yours have. I assume that's not important.

**Comment by JonathanTreffler** [comment]
> My artifact do not have the "vendor" folder yours have. I assume that's not important.

Yes, i just did a fast release for testing. For an actual release the vendor folder would be removed (because nextcloud will download the libraries in it automatically).

**Comment by JonathanTreffler** [comment]
> I managed to get it to work. Here is what I did:
> ```
> $ git clone https://github.com/JonathanTreffler/sharerenamer.git
> $ cd sharerenamer/
> $ git checkout v3
> $ npm ci
> $ npm run build
> $ rm -R node_modules
> ```
> 
> Then I deploy the **whole project folder** to NextCloud `apps` folder.
> 
> Usually, when you compile a project, it generates a deployable artifact. I was not expecting to have to deploy the whole project. I deleted the `node_modules` folder because it was not in the build you provided, and because it was very big (~150MB).


That is exactly the correct way :)

**Comment by JonathanTreffler** [comment]
I probably never adjusted the Makefile for v3. I will look into it.

**Comment by JonathanTreffler** [comment]
> Usually, when you compile a project, it generates a deployable artifact. I was not expecting to have to deploy the whole project.

Yes it compiles the js and vue files from src with the libraries from node_modules (installed by npm ci) and outputs to js/. It doesn't do anything with the php code, so you need to deploy the full folder structure.

**Comment by gaellafond** [comment]
Thanks @JonathanTreffler for taking the time to answer all my questions.
In the master branch, it creates a `.tar.gz` file in the `build` folder then it sign the archive using a private key (which is obviously not in the project sources). At least, that's how I understand the Makefile. Is that an old practice for old version of NextCloud? Will you have to implement something similar for NextCloud 20+?

**Comment by JonathanTreffler** [comment]
I will need to figure that out. It is still the principle, but lately everything has been automated with github actions. I will need to get a new key for the appstore (because of the owner transfer), wich should not be a problem.

**Comment by JonathanTreffler** [comment]
I will need to figure that out. It is still the principle, but lately everything has been automated with github actions. I will need to get a new key for the appstore (because of the owner transfer), wich should not be a problem.

**Comment by JonathanTreffler** [comment]
Finally all checks pass, so this can be merged :)

**Pull request merged**
